import type { Movie, UserProfile } from './types';
export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Oppenheimer',
    originalTitle: 'اوپنهایمر',
    description: 'J. Robert Oppenheimer and the Manhattan Project team race to build the atomic bomb during World War II. A profound exploration of genius, ambition, and the moral cost of scientific discovery.',
    posterUrl: 'https://images.unsplash.com/photo-1695556666596-f52a44f1d4a1?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1695556666596-f52a44f1d4a1?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.3,
    genres: ['Drama', 'Biography', 'History'],
    type: 'movie',
    duration: '180m',
    isFeatured: true,
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.']
  },
  {
    id: '2',
    title: 'Dune: Part Two',
    originalTitle: 'تلماسه: بخش دوم',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against those who destroyed his family. Epic continuation of the sci-fi saga.',
    posterUrl: 'https://images.unsplash.com/photo-1642838132718-d41d41c8dd52?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1642838132718-d41d41c8dd52?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.6,
    genres: ['Sci-Fi', 'Adventure'],
    type: 'movie',
    duration: '166m',
    isFeatured: true,
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson']
  },
  {
    id: '3',
    title: 'Barbie',
    originalTitle: 'باربی',
    description: 'Barbie and Ken discover the joys and perils of the real world. A brilliant satire that explores identity, feminism, and corporate power.',
    posterUrl: 'https://images.unsplash.com/photo-1682695796496-f4b203695ed8?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1682695796496-f4b203695ed8?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.2,
    genres: ['Comedy', 'Fantasy'],
    type: 'movie',
    duration: '114m',
    isFeatured: true,
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera']
  },
  {
    id: '4',
    title: 'Deadpool & Wolverine',
    originalTitle: 'ددپول و ولورین',
    description: 'Wade Wilson teams up with Wolverine to save his world. The ultimate R-rated superhero team-up with maximum violence and meta humor.',
    posterUrl: 'https://images.unsplash.com/photo-1622277772057-28b18f2ba514?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1622277772057-28b18f2ba514?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.1,
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    type: 'movie',
    duration: '128m',
    isFeatured: true,
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin']
  },
  {
    id: '5',
    title: 'Inside Out 2',
    originalTitle: 'داستان‌های درونی ۲',
    description: 'Riley navigates the challenges of puberty as new emotions join headquarters. Pixar masterpiece exploring teenage mental health.',
    posterUrl: 'https://images.unsplash.com/photo-1578631614396-5b5b78b11a4f?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1578631614396-5b5b78b11a4f?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.1,
    genres: ['Animation', 'Family', 'Comedy'],
    type: 'movie',
    duration: '96m',
    isFeatured: true,
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Kelsey Mann', 'Amy Poehler', 'Maya Hawke']
  },
  {
    id: '6',
    title: 'Godzilla Minus One',
    originalTitle: 'گودزیلا منهای یک',
    description: 'Post-WWII Japan faces Godzilla\'s wrath. A stunning reimagining that blends monster destruction with deep human drama.',
    posterUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.3,
    genres: ['Action', 'Drama', 'Sci-Fi'],
    type: 'movie',
    duration: '125m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Ryunosuke Kamiki', 'Minami Hamabe', 'Yuki Yamada']
  },
  {
    id: '7',
    title: 'Killers of the Flower Moon',
    originalTitle: 'قاتلان ماه گل',
    description: 'The true story of the Osage murders in 1920s Oklahoma. Martin Scorsese\'s epic crime drama about greed and betrayal.',
    posterUrl: 'https://images.unsplash.com/photo-1692628884664-59a3d8f1eecf?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1692628884664-59a3d8f1eecf?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Crime', 'Drama', 'History'],
    type: 'movie',
    duration: '206m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Leonardo DiCaprio', 'Robert De Niro', 'Lily Gladstone']
  },
  {
    id: '8',
    title: 'Poor Things',
    originalTitle: 'چیزهای فقیر',
    description: 'A young woman revived by a mad scientist embarks on a surreal journey of self-discovery. Yorgos Lanthimos\' bizarre masterpiece.',
    posterUrl: 'https://images.unsplash.com/photo-1701233433541-1b7b4a5f49d8?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1701233433541-1b7b4a5f49d8?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Sci-Fi', 'Comedy', 'Drama'],
    type: 'movie',
    duration: '141m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe']
  },
  {
    id: '9',
    title: 'Spider-Man: Across the Spider-Verse',
    originalTitle: 'مرد عنکبوتی: عبور از دنیای عنکبوتی',
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People. Animation perfection.',
    posterUrl: 'https://images.unsplash.com/photo-1635805731497-17d214ecda97?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1635805731497-17d214ecda97?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.6,
    genres: ['Animation', 'Action', 'Adventure'],
    type: 'movie',
    duration: '140m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Brian Tyree Henry']
  },
  {
    id: '10',
    title: 'Interstellar',
    originalTitle: 'میان‌ستاره‌ای',
    description: 'A team of explorers travel through a wormhole in space to ensure humanity\'s survival. Nolan\'s space epic masterpiece.',
    posterUrl: 'https://images.unsplash.com/photo-1489599169297-4cee0f5b5d0f?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1489599169297-4cee0f5b5d0f?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2014,
    rating: 8.7,
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    type: 'movie',
    duration: '169m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain']
  },
  {
    id: '11',
    title: 'Inception',
    originalTitle: 'تلقین',
    description: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',
    posterUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2010,
    rating: 8.8,
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    type: 'movie',
    duration: '148m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page']
  },
  {
    id: '12',
    title: 'The Holdovers',
    originalTitle: 'باقیمانده‌ها',
    description: 'A curmudgeonly instructor at a New England prep school forms an unlikely bond with a student and staff member during Christmas break.',
    posterUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Comedy', 'Drama'],
    type: 'movie',
    duration: '133m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Paul Giamatti', 'Da\'Vine Joy Randolph', 'Dominic Sessa']
  },
  {
    id: '13',
    title: 'Past Lives',
    originalTitle: 'زندگی‌های گذشته',
    description: 'Nora and Hae Sung, two childhood friends who thought they\'d never meet again after emigrating from South Korea, reunite 20 years later.',
    posterUrl: 'https://images.unsplash.com/photo-1519338381762-10df0cb9aff9?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1519338381762-10df0cb9aff9?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Romance', 'Drama'],
    type: 'movie',
    duration: '106m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Greta Lee', 'Teo Yoo', 'John Magaro']
  },
  {
    id: '14',
    title: 'Arcane',
    originalTitle: 'آرکین',
    description: 'Amid rising tensions between magic-tech wielders Piltover and the underworld of Zaun, two sisters are caught on opposite sides.',
    posterUrl: 'https://images.unsplash.com/photo-1635805731497-17d214ecda97?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1635805731497-17d214ecda97?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 9.0,
    genres: ['Animation', 'Action', 'Drama'],
    type: 'series',
    duration: '2 Seasons',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro']
  },
  {
    id: '15',
    title: 'Breaking Bad',
    originalTitle: 'برکینگ بد',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.',
    posterUrl: 'https://images.unsplash.com/photo-1611593738576-394c79986e26?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1611593738576-394c79986e26?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 9.5,
    genres: ['Crime', 'Drama', 'Thriller'],
    type: 'series',
    duration: '5 Seasons',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn']
  },
  {
    id: '16',
    title: 'Stranger Things',
    originalTitle: 'چیزهای عجیب',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments and terrifying supernatural forces.',
    posterUrl: 'https://images.unsplash.com/photo-1489599169297-4cee0f5b5d0f?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1489599169297-4cee0f5b5d0f?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.7,
    genres: ['Drama', 'Fantasy', 'Horror'],
    type: 'series',
    duration: '4 Seasons',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Winona Ryder', 'David Harbour', 'Millie Bobby Brown']
  },
  {
    id: '17',
    title: 'Anatomy of a Fall',
    originalTitle: 'آناتومی سقوط',
    description: 'A woman is suspected of her husband\'s murder. Gripping courtroom drama that questions truth and perception.',
    posterUrl: 'https://images.unsplash.com/photo-1574169208507-84376144848b?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1574169208507-84376144848b?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Drama', 'Mystery', 'Crime'],
    type: 'movie',
    duration: '151m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Sandra Hüller', 'Swann Arlaud', 'Milo Machado-Graner']
  },
  {
    id: '18',
    title: 'Guardians of the Galaxy Vol. 3',
    originalTitle: 'نگهبانان کهکشان ۳',
    description: 'Still reeling from his encounter with his father, Peter Quill rallies his team to defend the universe.',
    posterUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76bbb17e?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76bbb17e?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Action', 'Adventure', 'Comedy'],
    type: 'movie',
    duration: '150m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Chris Pratt', 'Zoe Saldaña', 'Dave Bautista']
  },
  {
    id: '19',
    title: 'Mission: Impossible - Dead Reckoning Part One',
    originalTitle: 'ماموریت غیرممکن: حساب مردگان - بخش اول',
    description: 'Ethan Hunt and his IMF team must track down a dangerous rogue AI. Tom Cruise\'s most spectacular stunts yet.',
    posterUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Action', 'Adventure', 'Thriller'],
    type: 'movie',
    duration: '163m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames']
  },
  {
    id: '20',
    title: 'The Last of Us',
    originalTitle: 'آخرین بازمانده از ما',
    description: 'After a global pandemic devastates civilization, infected survivors become violent creatures. Joel and Ellie embark on a perilous journey.',
    posterUrl: 'https://images.unsplash.com/photo-1618560887021-7e9e6a9415a5?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1618560887021-7e9e6a9415a5?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.8,
    genres: ['Drama', 'Horror', 'Post-Apocalyptic'],
    type: 'series',
    duration: '1 Season',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Gabriel Luna']
  },
  {
    id: '21',
    title: 'The Dark Knight',
    originalTitle: 'شوالیه تاریکی',
    description: 'Batman faces his greatest enemy yet, the Joker. The definitive superhero film that redefined the genre.',
    posterUrl: 'https://images.unsplash.com/photo-1542374305-9f5b71d443b4?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1542374305-9f5b71d443b4?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2008,
    rating: 9.0,
    genres: ['Action', 'Crime', 'Drama'],
    type: 'movie',
    duration: '152m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart']
  },
  {
    id: '22',
    title: 'The Matrix',
    originalTitle: 'ماتریکس',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    posterUrl: 'https://images.unsplash.com/photo-1573497019940-1e32e6f1dd09?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1573497019940-1e32e6f1dd09?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 1999,
    rating: 8.7,
    genres: ['Action', 'Sci-Fi'],
    type: 'movie',
    duration: '136m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss']
  },
  {
    id: '23',
    title: 'Pulp Fiction',
    originalTitle: 'داستان عامه‌پسند',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    posterUrl: 'https://images.unsplash.com/photo-1489599169297-4cee0f5b5d0f?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1489599169297-4cee0f5b5d0f?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 1994,
    rating: 8.9,
    genres: ['Crime', 'Drama'],
    type: 'movie',
    duration: '154m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson']
  },
  {
    id: '24',
    title: 'The Godfather',
    originalTitle: 'پدرخوانده',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    posterUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 1972,
    rating: 9.2,
    genres: ['Crime', 'Drama'],
    type: 'movie',
    duration: '175m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan']
  },
  {
    id: '25',
    title: 'Arrival',
    originalTitle: 'ورود',
    description: 'A linguist works with the military to communicate with alien lifeforms after giant spaceships land on Earth.',
    posterUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2016,
    rating: 8.0,
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    type: 'movie',
    duration: '116m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker']
  },
  {
    id: '26',
    title: 'Blade Runner 2049',
    originalTitle: 'بلید رانر ۲۰۴۹',
    description: 'A young blade runner embarks on a quest to track down former blade runner Rick Deckard.',
    posterUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2017,
    rating: 8.0,
    genres: ['Sci-Fi', 'Drama', 'Thriller'],
    type: 'movie',
    duration: '164m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas']
  },
  {
    id: '27',
    title: 'Parasite',
    originalTitle: 'انگل',
    description: 'Greed and class discrimination threaten the relationship between a wealthy family and their live-in help.',
    posterUrl: 'https://images.unsplash.com/photo-1574169208507-84376144848b?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1574169208507-84376144848b?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2019,
    rating: 8.5,
    genres: ['Thriller', 'Drama'],
    type: 'movie',
    duration: '132m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong']
  },
  {
    id: '28',
    title: 'John Wick: Chapter 4',
    originalTitle: 'جان ویک: فصل چهارم',
    description: 'John Wick uncovers a path to defeating the High Table. But before he can earn his freedom, Wick must face his most lethal foes yet.',
    posterUrl: 'https://images.unsplash.com/photo-1622277772057-28b18f2ba514?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1622277772057-28b18f2ba514?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.0,
    genres: ['Action', 'Thriller', 'Crime'],
    type: 'movie',
    duration: '169m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård']
  },
  {
    id: '29',
    title: 'Everything Everywhere All at Once',
    originalTitle: 'همه‌چیز همه‌جا به یکباره',
    description: 'A Chinese immigrant is swept up into an insane adventure where she alone can save existence by exploring other universes.',
    posterUrl: 'https://images.unsplash.com/photo-1676348926226-47a39f109f52?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1676348926226-47a39f109f52?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2022,
    rating: 8.0,
    genres: ['Action', 'Sci-Fi', 'Comedy'],
    type: 'movie',
    duration: '139m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan']
  },
  {
    id: '30',
    title: 'Dune',
    originalTitle: 'تلماسه',
    description: 'Paul Atreides travels to the most dangerous planet in the universe to ensure the future of his family and people.',
    posterUrl: 'https://images.unsplash.com/photo-1642838132718-d41d41c8dd52?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1642838132718-d41d41c8dd52?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2021,
    rating: 8.0,
    genres: ['Sci-Fi', 'Adventure'],
    type: 'movie',
    duration: '155m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Zendaya']
  },
  {
    id: '31',
    title: 'The Revenant',
    originalTitle: 'از گور برخاسته',
    description: 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear.',
    posterUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2015,
    rating: 8.0,
    genres: ['Adventure', 'Drama', 'Thriller'],
    type: 'movie',
    duration: '156m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Leonardo DiCaprio', 'Tom Hardy', 'Will Poulter']
  },
  {
    id: '32',
    title: 'Mad Max: Fury Road',
    originalTitle: 'مد مکس: جاده خشم',
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler with the help of a drifter named Max.',
    posterUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2015,
    rating: 8.1,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    type: 'movie',
    duration: '120m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult']
  },
  {
    id: '33',
    title: 'The Grand Budapest Hotel',
    originalTitle: 'هتل گرند بوداپست',
    description: 'A writer recounts his time as a young journalist befriending a legendary concierge at a glamorous European hotel.',
    posterUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2014,
    rating: 8.1,
    genres: ['Comedy', 'Drama'],
    type: 'movie',
    duration: '100m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Ralph Fiennes', 'F. Murray Abraham', 'Toni Collette']
  },
  {
    id: '34',
    title: 'Spider-Man: Into the Spider-Verse',
    originalTitle: 'مرد عنکبوتی: به درون دنیای عنکبوتی',
    description: 'Teen Miles Morales becomes Spider-Man and must work with five spider-powered individuals from other dimensions.',
    posterUrl: 'https://images.unsplash.com/photo-1635805731497-17d214ecda97?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1635805731497-17d214ecda97?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2018,
    rating: 8.4,
    genres: ['Animation', 'Action', 'Adventure'],
    type: 'movie',
    duration: '117m',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld']
  },
  {
    id: '35',
    title: 'House of the Dragon',
    originalTitle: 'خانه اژدها',
    description: 'The prequel to Game of Thrones follows the Targaryen dynasty. Dance of the dragons begins.',
    posterUrl: 'https://images.unsplash.com/photo-1642838132718-d41d41c8dd52?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1642838132718-d41d41c8dd52?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.4,
    genres: ['Drama', 'Fantasy', 'Action'],
    type: 'series',
    duration: '2 Seasons',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Matt Smith', 'Emma D\'Arcy', 'Olivia Cooke']
  },
  {
    id: '36',
    title: 'The Boys',
    originalTitle: 'پسران',
    description: 'A group of vigilantes set out to take down corrupt superheroes. Dark satire of superhero culture.',
    posterUrl: 'https://images.unsplash.com/photo-1622277772057-28b18f2ba514?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1622277772057-28b18f2ba514?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.7,
    genres: ['Action', 'Comedy', 'Crime'],
    type: 'series',
    duration: '4 Seasons',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Karl Urban', 'Jack Quaid', 'Antony Starr']
  },
  {
    id: '37',
    title: 'Silo',
    originalTitle: 'سیلو',
    description: 'Life in a toxic world protected by a thousand-foot concrete and steel silo. Mystery unfolds.',
    posterUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2023,
    rating: 8.1,
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    type: 'series',
    duration: '1 Season',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Rebecca Ferguson', 'Common', 'Tim Robbins']
  },
  {
    id: '38',
    title: 'Fallout',
    originalTitle: 'فال‌اوت',
    description: 'In a future post-apocalyptic Los Angeles, Lucy ventures above ground to rescue her father. Video game adaptation perfection.',
    posterUrl: 'https://images.unsplash.com/photo-1618560887021-7e9e6a9415a5?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1618560887021-7e9e6a9415a5?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.5,
    genres: ['Action', 'Adventure', 'Post-Apocalyptic'],
    type: 'series',
    duration: '1 Season',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Ella Purnell', 'Walton Goggins', 'Aaron Moten']
  },
  {
    id: '39',
    title: 'Shogun',
    originalTitle: 'شوگون',
    description: 'A mysterious European shipwreck survivor ends up in feudal Japan. Epic historical drama.',
    posterUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.8,
    genres: ['Drama', 'Adventure', 'History'],
    type: 'series',
    duration: '1 Season',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Hiroyuki Sanada', 'Cosmo Jarvis', 'Anna Sawai']
  },
  {
    id: '40',
    title: 'The Bear',
    originalTitle: 'خرس',
    description: 'A young fine-dining chef inherits his family\'s sandwich shop. Intense kitchen drama.',
    posterUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&w=342&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&w=1600&fit=crop',
    releaseYear: 2024,
    rating: 8.6,
    genres: ['Comedy', 'Drama'],
    type: 'series',
    duration: '3 Seasons',
    trailerUrl: 'dQw4w9WgXcQ',
    cast: ['Jeremy Allen White', 'Ebon Moss-Bachrach', 'Ayo Edebiri']
  }
];
export const MOCK_USER_PROFILE: UserProfile = {
  id: 'u1',
  name: 'Demo User',
  email: 'demo@streamvibe.com',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
  favorites: ['1', '5', '8'],
  watchlist: ['2', '12'],
  history: [
    { movieId: '3', progress: 45, watchedAt: Date.now() - 86400000 }
  ],
  preferredLanguage: 'en'
};